language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: mikeffrancis@gmail.com
  skip_cleanup: true
  api_key:
    secure: UYwLaPUnJ4/qTUtwjNBG9G5fD7peXAnKndQEY+84yEYX3Z4p5RKacusH9VRUz20WUrEiA6fgZmsthiHKSZQ7BZ3XaFyJp7XcTcHYPjY9gr4m2g04r0h1SPJq13IaZEqkDGXq0rG1FJWHA+IlpB2BsicCxbCh/BUfx13z2uKUOVpRrNnifSVZL4QojIaE+Z9fGylZZ6qw3bVZxIo96N+bhW4YxoHleMjcbDiW400VlCQ0+ElqSUhONFHaa35O2j1HGUlKdQa7RnA1X25esPVRP0LrsaYbETA/2wSCop9wT8+/Zwt7kO4kyNqTRy1ynsUxcmGr491XbkNNDr1z3u3uY2yflxwvcWYMg+DWv7/23QD0LPRIGMd7I/SxD9dSHDSKPtAe/zmZxDOFwt6DnoClLiqSCkBGy3N9BpPob8Qf3yps/w36obcjxrWikOaru0TMpKSOKks2jgoMLpZpn9MozfogZZShrVQkIoVSCEuGldwyl3Ni4PZsaxruwJxBhdJDrrMRs6sQpvw22+PJu0E9azpnF9rPORL923Fi0tNYGTEO6mGbCJ9DlK7hrl+RYCdZI2VJ0TrZSgPZknsPgJzPqfhLJM/igS9b+GgtC+n6RpTmClNP8uNwJ9eM6+yZ3dUor0chOHffg00IicYtyb/91tQp1ccJDzLDxwxedcthxKY=
  on:
    branch: master
    repo: mikefrancis/brewdog.js
